<i><b>Public AI</b></i>
<br>
###  &nbsp;&nbsp; **✎&nbsp;&nbsp;Week 1. Numpy Basis**
# Section 4. Numpy Array 추가와 변형

In [ ]:
# 우선 실행해주세요
import numpy as np

### 예제 데이터) 재수학원 학생들의 모의고사 성적표(월/학생)

|월/학생| 1 | 2 | 3 | 4 | 5 |6|7|8|9|
|---|----|---|---|---|---|---|---|---|---|
|A|390|382|393|362|375|392|358|367|396|
|B|300|297|311|320|336|340|342|357|360|
|C|187|190|167|164|163|171|178|151|180|
|D|298|267|254|302|300|308|380|384|392|
|E|96|78|390|80|72|396|68|92|400|

## 문제 1. 행렬의 shape 변경하기

* 수능을 대비하여 학생들에게 3개월마다의 성적의 평균(1\~3월 평균, 4\~6월 평균, 7\~9월 평균)을 저장하고 있는 표를 만들어주세요

정답 >>>
```python

np.array([[388.33333333, 376.33333333, 373.66666667],
       [302.66666667, 332.        , 353.        ],
       [181.33333333, 166.        , 169.66666667],
       [273.        , 303.33333333, 385.33333333],
       [188.        , 182.66666667, 186.66666667]])
```

* 참고 : numpy에서의 평균

numpy에서 축을 기준으로 평균을 구하는 방법은 다음과 같습니다.

`numpy_array.mean(axis=n)`

예시 >
```python
A = np.array([1,3,5,7,9])
A.mean(axis=0) # 결과 >> 5.0
```

In [ ]:
# 우선 실행해주세요
scores = np.array([
    [390,382,393,362,375,392,358,367,396],
    [300,297,311,320,336,340,342,357,360],
    [187,190,167,164,163,171,178,151,180],
    [298,267,254,302,300,308,380,384,392],
    [96,78,390,80,72,396,68,92,400]
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer1`에 담아주세요

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [ ]:
from numpy.testing import assert_array_almost_equal

assert 'answer1' in globals(), "결과를 answer1이라는 변수에 담아주세요!, answer1의 값을 보고 평가합니다."
assert isinstance(answer1, np.ndarray), "결과값들을 'numpy array'형식으로 담아주세요"

A = np.array([[388.33333333, 376.33333333, 373.66666667],
       [302.66666667, 332.        , 353.        ],
       [181.33333333, 166.        , 169.66666667],
       [273.        , 303.33333333, 385.33333333],
       [188.        , 182.66666667, 186.66666667]])

assert_array_almost_equal(A,answer1,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

### 예제 데이터) 재수학원 학생들의 월별 각 과목 성적표

* 3월 모의고사 성적표

|3월| 국어 | 수학 | 영어 | 과학 |
|---|----|---|---|---|
|A|100|93|100|100|
|B|63|100|48|100|
|C|82|17|32|36|
|D|71|68|57|58|
|E|100|100|100|90|

* 6월 모의고사 성적표

|6월| 국어 | 수학 | 영어 | 과학 |
|---|----|---|---|---|
|A|98|96|100|98|
|B|77|100|63|100|
|C|70|24|35|39|
|D|86|81|70|71|
|E|100|100|100|96|

* 9월 모의고사 성적표

|9월| 국어 | 수학 | 영어 | 과학 |
|---|----|---|---|---|
|A|100|100|100|96|
|B|87|100|73|100|
|C|91|21|31|33|
|D|100|100|96|96|
|E|100|100|100|100|

## 문제 2. 행렬의 shape 변경하기(2)

* 3월, 6월, 9월 모의고사는 국가에서 실시하는 중요한 모의고사입니다. 중요한 시험이니만큼 3월, 6월, 9월 모의고사 성적은 table-4에 과목별로 정리를 했습니다. table-4의 표를 과목을 첫번째 기준으로 만든 표인 table-5의 표로 바꿔주세요

![Imgur](https://i.imgur.com/HdV8aQd.png)

정답 >>> 
```python
np.array([[[100,  98, 100],
        [ 63,  77,  87],
        [ 82,  70,  91],
        [ 71,  86, 100],
        [100, 100, 100]],

       [[ 93,  96, 100],
        [100, 100, 100],
        [ 17,  24,  21],
        [ 68,  81, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [ 48,  63,  73],
        [ 32,  35,  31],
        [ 57,  70,  96],
        [100, 100, 100]],

       [[100,  98,  96],
        [100, 100, 100],
        [ 36,  39,  33],
        [ 58,  71,  96],
        [ 90,  96, 100]]])
```

In [ ]:
# 우선 입력해주세요
march_score = np.array([
    [100, 93, 100, 100],
    [63, 100, 48, 100],
    [82, 17, 32, 36],
    [71, 68, 57, 58],
    [100, 100, 100, 90]
])

june_score = np.array([
    [98, 96, 100, 98],
    [77, 100, 63, 100],
    [70, 24, 35, 39],
    [86, 81, 70, 71],
    [100, 100, 100, 96],
])

september_score = np.array([
    [100, 100, 100, 96],
    [87, 100, 73, 100],
    [91, 21, 31, 33],
    [100, 100, 96, 96],
    [100, 100, 100, 100]
])

important_score = np.stack((march_score, june_score, september_score))
important_score

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer2`에 담아주세요

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [ ]:
from numpy.testing import assert_array_almost_equal

assert 'answer2' in globals(), "결과를 answer2라는 변수에 담아주세요!, answer2의 값을 보고 평가합니다."
assert isinstance(answer2, np.ndarray), "결과값들을 'numpy array'형식으로 담아주세요"

A = np.array([[[100,  98, 100],
        [ 63,  77,  87],
        [ 82,  70,  91],
        [ 71,  86, 100],
        [100, 100, 100]],

       [[ 93,  96, 100],
        [100, 100, 100],
        [ 17,  24,  21],
        [ 68,  81, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [ 48,  63,  73],
        [ 32,  35,  31],
        [ 57,  70,  96],
        [100, 100, 100]],

       [[100,  98,  96],
        [100, 100, 100],
        [ 36,  39,  33],
        [ 58,  71,  96],
        [ 90,  96, 100]]])

assert_array_almost_equal(A,answer2,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

### 예제 데이터) 2012년~2017년 삼성전자 분기별 매출

| (단위:조원) | 1분기 | 2분기 | 3분기 | 4분기 |
| ------ | ----- | ----- | ----- | ----- |
| 2012년 | 45.27 | 47.60 | 52.18 | 56.06 |
| 2013년 | 52.87 | 57.46 | 59.08 | 59.28 |
| 2014년 | 53.68 | 52.35 | 47.45 | 52.73 |
| 2015년 | 47.12 | 48.54 | 51.68 | 53.32 |
| 2016년 | 49.78 | 50.94 | 47.82 | 53.33 |
| 2017년 | 50.55 | 61.99 | 62.05 | 65.98 |

## 문제 3. np.concatenate를 사용해 data 추가하기(1)

* 위의 표에 다음과 같은 2018년 데이터를 추가한 표를 만들어주세요

| (단위:조원) | 1분기 | 2분기 | 3분기 | 4분기 |
| ------ | ----- | ----- | ----- | ----- |
| 2018년 | 60.56 | 58.48 | 65.46 | 59.27 |

정답 >>>
```python
np.array([
    [45.27, 47.60, 52.18, 56.06],
    [52.87, 57.46, 59.08, 59.28],
    [53.68, 52.35, 47.45, 52.73],
    [47.12, 48.54, 51.68, 53.32],
    [49.78, 50.94, 47.82, 53.33],
    [50.55, 61.99, 62.05, 65.98],
    [60.56, 58.48, 65.46, 59.27]
])
```

In [ ]:
# 우선 실행해주세요
sales = np.array([
    [45.27, 47.60, 52.18, 56.06],
    [52.87, 57.46, 59.08, 59.28],
    [53.68, 52.35, 47.45, 52.73],
    [47.12, 48.54, 51.68, 53.32],
    [49.78, 50.94, 47.82, 53.33],
    [50.55, 61.99, 62.05, 65.98],
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer3`에 담아주세요

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [ ]:
from numpy.testing import assert_array_almost_equal

assert 'answer3' in globals(), "결과를 answer3이라는 변수에 담아주세요!, answer3의 값을 보고 평가합니다."
assert isinstance(answer3, np.ndarray), "결과값들을 'numpy array'형식으로 담아주세요"

A = np.array([[45.27, 47.6 , 52.18, 56.06],
       [52.87, 57.46, 59.08, 59.28],
       [53.68, 52.35, 47.45, 52.73],
       [47.12, 48.54, 51.68, 53.32],
       [49.78, 50.94, 47.82, 53.33],
       [50.55, 61.99, 62.05, 65.98],
       [60.56, 58.48, 65.46, 59.27]])

assert_array_almost_equal(A,answer3,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

## 문제 4. np.concatenate를 사용해 data 추가하기(2)

* 아래의 표와 같이 위의 표에 연도별 매출의 총합을 추가한 표를 만들어주세요

| (단위:조원) | 1분기 | 2분기 | 3분기 | 4분기 | 매출
| ------ | ----- | ----- | ----- | ----- | ----- |
| 2012년 | 45.27 | 47.60 | 52.18 | 56.06 | 201.11 |
| 2013년 | 52.87 | 57.46 | 59.08 | 59.28 | 228.69 |
| 2014년 | 53.68 | 52.35 | 47.45 | 52.73 | 206.21 |
| 2015년 | 47.12 | 48.54 | 51.68 | 53.32 | 200.66 |
| 2016년 | 49.78 | 50.94 | 47.82 | 53.33 | 201.87 |
| 2017년 | 50.55 | 61.99 | 62.05 | 65.98 | 240.57 |

* 변경과정

![Imgur](https://i.imgur.com/Ep1WhZrl.png)

정답 >>>
```python
np.array([[ 45.27,  47.6 ,  52.18,  56.06, 201.11],
       [ 52.87,  57.46,  59.08,  59.28, 228.69],
       [ 53.68,  52.35,  47.45,  52.73, 206.21],
       [ 47.12,  48.54,  51.68,  53.32, 200.66],
       [ 49.78,  50.94,  47.82,  53.33, 201.87],
       [ 50.55,  61.99,  62.05,  65.98, 240.57]])
```

In [ ]:
# 우선 실행해주세요
sales = np.array([
    [45.27, 47.60, 52.18, 56.06],
    [52.87, 57.46, 59.08, 59.28],
    [53.68, 52.35, 47.45, 52.73],
    [47.12, 48.54, 51.68, 53.32],
    [49.78, 50.94, 47.82, 53.33],
    [50.55, 61.99, 62.05, 65.98],
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer4`에 담아주세요

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [ ]:
from numpy.testing import assert_array_almost_equal

assert 'answer4' in globals(), "결과를 answer4라는 변수에 담아주세요!, answer4의 값을 보고 평가합니다."
assert isinstance(answer4, np.ndarray), "결과값들을 'numpy array'형식으로 담아주세요"

A = np.array([[ 45.27,  47.6 ,  52.18,  56.06, 201.11],
       [ 52.87,  57.46,  59.08,  59.28, 228.69],
       [ 53.68,  52.35,  47.45,  52.73, 206.21],
       [ 47.12,  48.54,  51.68,  53.32, 200.66],
       [ 49.78,  50.94,  47.82,  53.33, 201.87],
       [ 50.55,  61.99,  62.05,  65.98, 240.57]])

assert_array_almost_equal(A,answer4,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

### 예제 데이터) 득점순위에 따른 리그별 축구선수들의 데이터

* 영국리그 선수들의 데이터

| 영국 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 영국1등 |22 |1 |87 | 42 | 36 |
| 영국2등 |22 |5 |93 | 40 | 36 | 
| 영국3등 |22 |8 |135 | 64 | 38 |
| 영국4등 |21 |8 |117 | 43 | 33 |
| 영국5등 |16 |15 |94 | 43 | 37 |
| 영국6등 |12 |6 |74 | 29 | 31 |


* 스페인리그 선수들의 데이터

| 스페인 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 스페인1등 |36 |13 |171 | 88 | 34 |
| 스페인2등 |21 |6 |111 | 58 | 33 | 
| 스페인3등 |21 |6 |104 | 45 | 36 |
| 스페인4등 |20 |6 |70 | 31 | 27 |
| 스페인5등 |19 |0 |80 | 40 | 32 |
| 스페인6등 |15 |8 |112 | 46 | 37 |

* 이탈리아리그 선수들의 데이터

| 이탈리아 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 이탈리아1등 |26 |8 |119 | 70 | 37 |
| 이탈리아2등 |23 |7 |92 | 58 | 37 | 
| 이탈리아3등 |22 |0 |91 | 60 | 37 |
| 이탈리아4등 |21 |6 |136 | 77 | 31 |
| 이탈리아5등 |17 |3 |92 | 59 | 35 |
| 이탈리아6등 |16 |9 |76 | 45 | 35 |

## 문제 5. np.stack

* 예제 데이터의 표는 각 리그 별로 축구 선수들의 데이터들을 나타낸 것입니다. 각 리그의 데이터들을 합쳐 아래 정답과 같이 데이터별로 선수의 득점순위를 비교하며 국가순서대로 하나의 데이터로 합쳐주세요


* 힌트 : **축과 shape**에 집중해주세요


* 영국리그 선수들의 데이터

| 영국 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 영국1등 |22 |1 |87 | 42 | 36 |
| 영국2등 |22 |5 |93 | 40 | 36 | 
| 영국3등 |22 |8 |135 | 64 | 38 |
| 영국4등 |21 |8 |117 | 43 | 33 |
| 영국5등 |16 |15 |94 | 43 | 37 |
| 영국6등 |12 |6 |74 | 29 | 31 |


* 스페인리그 선수들의 데이터

| 스페인 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 스페인1등 |36 |13 |171 | 88 | 34 |
| 스페인2등 |21 |6 |111 | 58 | 33 | 
| 스페인3등 |21 |6 |104 | 45 | 36 |
| 스페인4등 |20 |6 |70 | 31 | 27 |
| 스페인5등 |19 |0 |80 | 40 | 32 |
| 스페인6등 |15 |8 |112 | 46 | 37 |

* 이탈리아리그 선수들의 데이터

| 이탈리아 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 이탈리아1등 |26 |8 |119 | 70 | 37 |
| 이탈리아2등 |23 |7 |92 | 58 | 37 | 
| 이탈리아3등 |22 |0 |91 | 60 | 37 |
| 이탈리아4등 |21 |6 |136 | 77 | 31 |
| 이탈리아5등 |17 |3 |92 | 59 | 35 |
| 이탈리아6등 |16 |9 |76 | 45 | 35 |

정답 > 
```python
np.array([[[ 22,   1,  87,  42,  36],
        [ 22,   5,  93,  40,  36],
        [ 22,   8, 135,  64,  38],
        [ 21,   8, 117,  43,  33],
        [ 16,  15,  94,  43,  37],
        [ 12,   6,  74,  29,  31]],

       [[ 36,  13, 171,  88,  34],
        [ 21,   6, 111,  58,  33],
        [ 21,   6, 104,  45,  36],
        [ 20,   6,  70,  31,  27],
        [ 19,   0,  80,  40,  32],
        [ 15,   8, 112,  46,  37]],

       [[ 26,   8, 119,  70,  37],
        [ 23,   7,  92,  58,  37],
        [ 22,   0,  91,  60,  37],
        [ 21,   6, 136,  77,  31],
        [ 17,   3,  92,  59,  35],
        [ 16,   9,  76,  45,  35]]])
```

In [ ]:
# 우선 입력해주세요
england = np.array([
    [22,1,87,42,36],
    [22,5,93,40,36],
    [22,8,135,64,38],
    [21,8,117,43,33],
    [16,15,94,43,37],
    [12,6,74,29,31]
])

spain = np.array([
    [36,13,171,88,34],
    [21,6,111,58,33],
    [21,6,104,45,36],
    [20,6,70,31,27],
    [19,0,80,40,32],
    [15,8,112,46,37]
])

italy = np.array([
    [26,8,119,70,37],
    [23,7,92,58,37],
    [22,0,91,60,37],
    [21,6,136,77,31],
    [17,3,92,59,35],
    [16,9,76,45,35]
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer5`에 담아주세요

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [ ]:
from numpy.testing import assert_array_almost_equal

assert 'answer5' in globals(), "결과를 answer5라는 변수에 담아주세요!, answer5의 값을 보고 평가합니다."
assert isinstance(answer5, np.ndarray), "결과값들을 'numpy array'형식으로 담아주세요"

A = np.array([[[ 22,   1,  87,  42,  36],
        [ 22,   5,  93,  40,  36],
        [ 22,   8, 135,  64,  38],
        [ 21,   8, 117,  43,  33],
        [ 16,  15,  94,  43,  37],
        [ 12,   6,  74,  29,  31]],

       [[ 36,  13, 171,  88,  34],
        [ 21,   6, 111,  58,  33],
        [ 21,   6, 104,  45,  36],
        [ 20,   6,  70,  31,  27],
        [ 19,   0,  80,  40,  32],
        [ 15,   8, 112,  46,  37]],

       [[ 26,   8, 119,  70,  37],
        [ 23,   7,  92,  58,  37],
        [ 22,   0,  91,  60,  37],
        [ 21,   6, 136,  77,  31],
        [ 17,   3,  92,  59,  35],
        [ 16,   9,  76,  45,  35]]])

assert_array_almost_equal(A,answer5,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

## 문제 6. 새로운 데이터 추가하기

* 문제 5에 있는 테이블에 각 리그 7등들의 데이터를 추가해주세요  


* 힌트 : **축과 shape**에 집중해주세요


* 영국리그 7등들의 데이터

| 영국 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 영국7등 |11 |13 |78 | 38 | 38 |

* 스페인리그 7등들의 데이터

| 스페인 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 스페인7등 |15 |2 |121 | 57 | 38 |

* 이탈리아리그 7등들의 데이터

| 이탈리아 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 이탈리아7등 |16 |4 |82 | 58 | 38 |

<br><br>

* 변경 과정 

![Imgur](https://i.imgur.com/UGKpbDX.png)

정답 > 
```python
np.array([[[ 22,   1,  87,  42,  36],
        [ 22,   5,  93,  40,  36],
        [ 22,   8, 135,  64,  38],
        [ 21,   8, 117,  43,  33],
        [ 16,  15,  94,  43,  37],
        [ 12,   6,  74,  29,  31],
        [ 11,  13,  78,  38,  38]],

       [[ 36,  13, 171,  88,  34],
        [ 21,   6, 111,  58,  33],
        [ 21,   6, 104,  45,  36],
        [ 20,   6,  70,  31,  27],
        [ 19,   0,  80,  40,  32],
        [ 15,   8, 112,  46,  37],
        [ 15,   2, 121,  57,  38]],

       [[ 26,   8, 119,  70,  37],
        [ 23,   7,  92,  58,  37],
        [ 22,   0,  91,  60,  37],
        [ 21,   6, 136,  77,  31],
        [ 17,   3,  92,  59,  35],
        [ 16,   9,  76,  45,  35],
        [ 16,   4,  82,  58,  38]]])
```

In [ ]:
# 우선 입력해주세요
england = np.array([
    [22,1,87,42,36],
    [22,5,93,40,36],
    [22,8,135,64,38],
    [21,8,117,43,33],
    [16,15,94,43,37],
    [12,6,74,29,31]
])

spain = np.array([
    [36,13,171,88,34],
    [21,6,111,58,33],
    [21,6,104,45,36],
    [20,6,70,31,27],
    [19,0,80,40,32],
    [15,8,112,46,37]
])

italy = np.array([
    [26,8,119,70,37],
    [23,7,92,58,37],
    [22,0,91,60,37],
    [21,6,136,77,31],
    [17,3,92,59,35],
    [16,9,76,45,35]
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer6`에 담아주세요

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [ ]:
from numpy.testing import assert_array_almost_equal

assert 'answer6' in globals(), "결과를 answer6이라는 변수에 담아주세요!, answer6의 값을 보고 평가합니다."
assert isinstance(answer6, np.ndarray), "결과값들을 'numpy array'형식으로 담아주세요"

A = np.array([[[ 22,   1,  87,  42,  36],
        [ 22,   5,  93,  40,  36],
        [ 22,   8, 135,  64,  38],
        [ 21,   8, 117,  43,  33],
        [ 16,  15,  94,  43,  37],
        [ 12,   6,  74,  29,  31],
        [ 11,  13,  78,  38,  38]],

       [[ 36,  13, 171,  88,  34],
        [ 21,   6, 111,  58,  33],
        [ 21,   6, 104,  45,  36],
        [ 20,   6,  70,  31,  27],
        [ 19,   0,  80,  40,  32],
        [ 15,   8, 112,  46,  37],
        [ 15,   2, 121,  57,  38]],

       [[ 26,   8, 119,  70,  37],
        [ 23,   7,  92,  58,  37],
        [ 22,   0,  91,  60,  37],
        [ 21,   6, 136,  77,  31],
        [ 17,   3,  92,  59,  35],
        [ 16,   9,  76,  45,  35],
        [ 16,   4,  82,  58,  38]]])
assert_array_almost_equal(A,answer6,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

#  

<hr>
<div>
    Copyright(c) 2019 by Public AI. All rights reserved.<br>
    Writen by PAI, DoYeong Kim ( ka2k@publicai.co.kr )  last updated on 2019/07/12
</div>
<hr>